### ISSUE TITLE
Request for ldap commands.

### ISSUE THREAD

**Issue by mookkiah** [BobDotMe/bob#10]
Can we have BoB pod powered with ldap commands?

https://docs.oracle.com/cd/B10501_01/network.920/a96579/comtools.htm
https://docs.oracle.com/cd/E19424-01/820-4809/ganwc/index.html
https://backstage.forgerock.com/docs/opendj/3/admin-guide/#cli-constraints

**Comment by rsliotta** [comment]
Will be in release 0.9.8
